### PR TITLE
Add newsletter subscribe button to the header and sticky nav

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Adds a `Subscribe` button to the header and sticky nav

Desktop:
Screen Shot 2020-04-06 at 10 34 03 AM

Sticky:
Screen Shot 2020-04-06 at 10 34 10 AM

Mobile:
Screen Shot 2020-04-06 at 10 34 17 AM

## Why

For #7 

## Testing/Questions

Features that this PR affects:

- Global nav and sticky nav

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [ ] Is the blue color ok?

Steps to test this PR:

1. View the global nav, sticky nav, and mobile nav and verify they all look ok.

### CODE REVIEW

**Comment by benlk** [comment]
Screen Shot 2020-04-08 at 23 22 51

How do we want to handle the narrowest screens?

**Comment by joshdarby** [comment]
@benlk I think it's fine like that. Even at 200px width it still doesn't look horrible. Plus, if someone is using a screen at 200px I think they'll see more issues than just the subscribe button

Screen Shot 2020-04-09 at 9 14 57 AM

**Comment by benlk** [comment]
There are probably still folks using 320px iPhones, though.

**Comment by joshdarby** [comment]
Right, but it still looks ok at that size. 

Screen Shot 2020-04-09 at 11 31 39 AM

**Comment by joshdarby** [comment]
@benlk can this be merged or do you have more concerns with it?

**Comment by benlk** [comment]
If you're okay with it, then sure. I don't like how the sticky nav doubles in height, but we don't have a good fix for that.

**Pull request merged**
